# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Técnicas de Gráficos por Computadora
author: TGC
email: tgcentregas@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
 Página web de Técnicas de Gráficos por Computadora de la UTN FRBA.

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  # generate social links in footer
  social_links:
    twitter: tgcutn
    github: tgc-utn
    facebook: tgcutn
    youtube: tgcentregas

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
