# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Técnicas de Gráficos por Computadora
email: tgcentregas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Página web de Técnicas de Gráficos por Computadora de la UTN FRBA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tgcutn.com.ar" # the base hostname & protocol for your site
facebook_group: tgcutn
github_username: tgc-utn
google_group: tecnicasdegraficosporcomputadora
twitter_username: tgcutn
youtube_username: tgcentregas

# Build settings
markdown: kramdown

# For Travisci
exclude: [vendor]
